version: '3'
services:
  bpmrx-seed:
    build: .
    hostname: bpmrx-seed
    environment:
    - RXBPM_SEED_NODES=bpmrx-seed

  bpm-rx:
    build: .
    hostname: bpm-rx
    depends_on:
      - bpmrx-seed
    environment:
      - RXBPM_SEED_NODES=bpmrx-seed
    links:
    - bpmrx-seed